---
- name: Init dconf
  ansible.builtin.include_tasks:
    file: _init.yml

- name: Cleanup Mate autostart
  become: true
  ansible.builtin.file:
    path: /etc/xdg/autostart/{{ item }}
    state: absent
  with_items: '{{ client_autostart_absent_list }}'
  async: 3600
  poll: 0
